name: Webhook Aniversariantes
on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  disparar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install requests google-cloud-bigquery google-auth db-dtypes pandas
      - run: python webhook_aniversariantes.py
        env:
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GCP_SA_KEY }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
